### ISSUE TITLE
Cannot import the stylesheet.png image from the zelda_mini_clone project

### ISSUE THREAD

**Issue by henriquekirchheck** [henriquekirchheck/curso-dankicode-jogos#1]
```
Exception in thread "main" java.lang.IllegalArgumentException: input == null!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1400)
        at zelda_mini_clone.Spritesheet.<init>(Spritesheet.java:14)
        at zelda_mini_clone.Game.<init>(Game.java:21)
        at zelda_mini_clone.Game.main(Game.java:51)
```

**Comment by henriquekirchheck** [comment]
Fixed with a vscode config
